### ISSUE TITLE
Training DeepCAD model from scratch on MeSA dataset

### ISSUE THREAD

**Issue by BoudabousSafa** [leoaoli1/DeepCAD#2]
Hi,

I'm facing a problem training the DeepCAD model on MeSA dataset as the loss doesn't converge and the model predicts only zeros.

Could you please give me more details about:
* How many epochs have you trained the model ?
* Have you done some preprocessing before storing data on HDF file (I noticed that for the example hdf the ECG values are higher than the ones from EDF file).

Thank you

**Comment by leoaoli1** [comment]
Hello,

- How many epochs have you trained the model ?
We have trained the model for approximately 20 epochs. 

- Have you done some preprocessing before storing data on HDF file (I noticed that for the example hdf the ECG values are higher than the ones from EDF file).
We did not preprocess the ECG data before storing it. When loading the data from the HDF file, we made an adjustment by reversing the ECG values to ensure that R peaks became positive.
